-- Select all employees table data
SELECT * FROM classicmodels.employees;

-- Select all customers table data
SELECT * FROM classicmodels.customers;

-- Left Join
SELECT FIRSTNAME, LASTNAME, CUSTOMERNAME 
FROM 
CLASSICMODELS.EMPLOYEES T1 LEFT JOIN CLASSICMODELS.CUSTOMERS T2
ON T1.EMPLOYEENUMBER = T2.SALESREPEMPLOYEENUMBER;

-- Left Join with all data
SELECT * 
FROM 
CLASSICMODELS.EMPLOYEES T1 LEFT JOIN CLASSICMODELS.CUSTOMERS T2
ON T1.EMPLOYEENUMBER = T2.SALESREPEMPLOYEENUMBER;

-- Left Join with all data and also where condition eg 1
SELECT * 
FROM 
CLASSICMODELS.EMPLOYEES T1 LEFT JOIN CLASSICMODELS.CUSTOMERS T2
ON T1.EMPLOYEENUMBER = T2.SALESREPEMPLOYEENUMBER
where t2.customernumber is null;

-- Left Join with all data and also where condition eg 2
SELECT * 
FROM 
CLASSICMODELS.EMPLOYEES T1 LEFT JOIN CLASSICMODELS.CUSTOMERS T2
ON T1.EMPLOYEENUMBER = T2.SALESREPEMPLOYEENUMBER
where 
t2.customernumber is null and jobTitle = "Sales Rep";

-- Right Join
SELECT FIRSTNAME, LASTNAME, CUSTOMERNAME 
FROM 
CLASSICMODELS.EMPLOYEES T1 RIGHT JOIN CLASSICMODELS.CUSTOMERS T2
ON T1.EMPLOYEENUMBER = T2.SALESREPEMPLOYEENUMBER;

